//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class GenericFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors {
            get {
                return this.wrappedErrorsField;
            }
            set {
                this.wrappedErrorsField = value;
                this.RaisePropertyChanged("WrappedErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class GenericFaultParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class WrappedError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerDataGroupExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerDataGroupInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string codeField;
        
        private int taxClassIdField;
        
        private string taxClassNameField;
        
        private CustomerDataGroupExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int taxClassId {
            get {
                return this.taxClassIdField;
            }
            set {
                this.taxClassIdField = value;
                this.RaisePropertyChanged("taxClassId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string taxClassName {
            get {
                return this.taxClassNameField;
            }
            set {
                this.taxClassNameField = value;
                this.RaisePropertyChanged("taxClassName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public CustomerDataGroupExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerGroupRepositoryV1GetByIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomerDataGroupInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupInterface result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerGroupRepositoryV1GetByIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", ConfigurationName="MagentoCustGroupRespository.customerGroupRepositoryV1PortType")]
    public interface customerGroupRepositoryV1PortType {
        
        // CODEGEN: Generating message contract since the operation customerGroupRepositoryV1GetById is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1GetById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.GenericFault), Action="customerGroupRepositoryV1GetById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdResponse1 customerGroupRepositoryV1GetById(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdResponse1> customerGroupRepositoryV1GetByIdAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdRequest1 request);
        
        // CODEGEN: Generating message contract since the operation customerGroupRepositoryV1GetList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.GenericFault), Action="customerGroupRepositoryV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListResponse1 customerGroupRepositoryV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListResponse1> customerGroupRepositoryV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation customerGroupRepositoryV1Save is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1Save", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.GenericFault), Action="customerGroupRepositoryV1Save", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveResponse1 customerGroupRepositoryV1Save(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1Save", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveResponse1> customerGroupRepositoryV1SaveAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveRequest1 request);
        
        // CODEGEN: Generating message contract since the operation customerGroupRepositoryV1DeleteById is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1DeleteById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.GenericFault), Action="customerGroupRepositoryV1DeleteById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdResponse1 customerGroupRepositoryV1DeleteById(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="customerGroupRepositoryV1DeleteById", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdResponse1> customerGroupRepositoryV1DeleteByIdAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1GetByIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetByIdRequest customerGroupRepositoryV1GetByIdRequest;
        
        public customerGroupRepositoryV1GetByIdRequest1() {
        }
        
        public customerGroupRepositoryV1GetByIdRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetByIdRequest customerGroupRepositoryV1GetByIdRequest) {
            this.customerGroupRepositoryV1GetByIdRequest = customerGroupRepositoryV1GetByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1GetByIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetByIdResponse customerGroupRepositoryV1GetByIdResponse;
        
        public customerGroupRepositoryV1GetByIdResponse1() {
        }
        
        public customerGroupRepositoryV1GetByIdResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetByIdResponse customerGroupRepositoryV1GetByIdResponse) {
            this.customerGroupRepositoryV1GetByIdResponse = customerGroupRepositoryV1GetByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerGroupRepositoryV1GetListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteriaInterface searchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("searchCriteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class FrameworkSearchCriteriaInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups {
            get {
                return this.filterGroupsField;
            }
            set {
                this.filterGroupsField = value;
                this.RaisePropertyChanged("filterGroups");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders {
            get {
                return this.sortOrdersField;
            }
            set {
                this.sortOrdersField = value;
                this.RaisePropertyChanged("sortOrders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
                this.RaisePropertyChanged("pageSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified {
            get {
                return this.currentPageFieldSpecified;
            }
            set {
                this.currentPageFieldSpecified = value;
                this.RaisePropertyChanged("currentPageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class FrameworkSearchFilterGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
                this.RaisePropertyChanged("filters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class FrameworkFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType {
            get {
                return this.conditionTypeField;
            }
            set {
                this.conditionTypeField = value;
                this.RaisePropertyChanged("conditionType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class FrameworkSortOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("direction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerGroupRepositoryV1GetListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomerDataGroupSearchResultsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupSearchResultsInterface result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerDataGroupSearchResultsInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomerDataGroupInterface[] itemsField;
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CustomerDataGroupInterface[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FrameworkSearchCriteriaInterface searchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("searchCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1GetListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetListRequest customerGroupRepositoryV1GetListRequest;
        
        public customerGroupRepositoryV1GetListRequest1() {
        }
        
        public customerGroupRepositoryV1GetListRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetListRequest customerGroupRepositoryV1GetListRequest) {
            this.customerGroupRepositoryV1GetListRequest = customerGroupRepositoryV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1GetListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetListResponse customerGroupRepositoryV1GetListResponse;
        
        public customerGroupRepositoryV1GetListResponse1() {
        }
        
        public customerGroupRepositoryV1GetListResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetListResponse customerGroupRepositoryV1GetListResponse) {
            this.customerGroupRepositoryV1GetListResponse = customerGroupRepositoryV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerGroupRepositoryV1SaveRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomerDataGroupInterface groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupInterface group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("group");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerGroupRepositoryV1SaveResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomerDataGroupInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CustomerDataGroupInterface result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1SaveRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1SaveRequest customerGroupRepositoryV1SaveRequest;
        
        public customerGroupRepositoryV1SaveRequest1() {
        }
        
        public customerGroupRepositoryV1SaveRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1SaveRequest customerGroupRepositoryV1SaveRequest) {
            this.customerGroupRepositoryV1SaveRequest = customerGroupRepositoryV1SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1SaveResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1SaveResponse customerGroupRepositoryV1SaveResponse;
        
        public customerGroupRepositoryV1SaveResponse1() {
        }
        
        public customerGroupRepositoryV1SaveResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1SaveResponse customerGroupRepositoryV1SaveResponse) {
            this.customerGroupRepositoryV1SaveResponse = customerGroupRepositoryV1SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerGroupRepositoryV1DeleteByIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1")]
    public partial class CustomerGroupRepositoryV1DeleteByIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1DeleteByIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1DeleteByIdRequest customerGroupRepositoryV1DeleteByIdRequest;
        
        public customerGroupRepositoryV1DeleteByIdRequest1() {
        }
        
        public customerGroupRepositoryV1DeleteByIdRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1DeleteByIdRequest customerGroupRepositoryV1DeleteByIdRequest) {
            this.customerGroupRepositoryV1DeleteByIdRequest = customerGroupRepositoryV1DeleteByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class customerGroupRepositoryV1DeleteByIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=customerGroupRepositoryV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1DeleteByIdResponse customerGroupRepositoryV1DeleteByIdResponse;
        
        public customerGroupRepositoryV1DeleteByIdResponse1() {
        }
        
        public customerGroupRepositoryV1DeleteByIdResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1DeleteByIdResponse customerGroupRepositoryV1DeleteByIdResponse) {
            this.customerGroupRepositoryV1DeleteByIdResponse = customerGroupRepositoryV1DeleteByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface customerGroupRepositoryV1PortTypeChannel : Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class customerGroupRepositoryV1PortTypeClient : System.ServiceModel.ClientBase<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType>, Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType {
        
        public customerGroupRepositoryV1PortTypeClient() {
        }
        
        public customerGroupRepositoryV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public customerGroupRepositoryV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public customerGroupRepositoryV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public customerGroupRepositoryV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType.customerGroupRepositoryV1GetById(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdRequest1 request) {
            return base.Channel.customerGroupRepositoryV1GetById(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetByIdResponse customerGroupRepositoryV1GetById(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetByIdRequest customerGroupRepositoryV1GetByIdRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdRequest1();
            inValue.customerGroupRepositoryV1GetByIdRequest = customerGroupRepositoryV1GetByIdRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1GetById(inValue);
            return retVal.customerGroupRepositoryV1GetByIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType.customerGroupRepositoryV1GetByIdAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdRequest1 request) {
            return base.Channel.customerGroupRepositoryV1GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdResponse1> customerGroupRepositoryV1GetByIdAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetByIdRequest customerGroupRepositoryV1GetByIdRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetByIdRequest1();
            inValue.customerGroupRepositoryV1GetByIdRequest = customerGroupRepositoryV1GetByIdRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType.customerGroupRepositoryV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListRequest1 request) {
            return base.Channel.customerGroupRepositoryV1GetList(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetListResponse customerGroupRepositoryV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetListRequest customerGroupRepositoryV1GetListRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListRequest1();
            inValue.customerGroupRepositoryV1GetListRequest = customerGroupRepositoryV1GetListRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1GetList(inValue);
            return retVal.customerGroupRepositoryV1GetListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType.customerGroupRepositoryV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListRequest1 request) {
            return base.Channel.customerGroupRepositoryV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListResponse1> customerGroupRepositoryV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1GetListRequest customerGroupRepositoryV1GetListRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1GetListRequest1();
            inValue.customerGroupRepositoryV1GetListRequest = customerGroupRepositoryV1GetListRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType.customerGroupRepositoryV1Save(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveRequest1 request) {
            return base.Channel.customerGroupRepositoryV1Save(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1SaveResponse customerGroupRepositoryV1Save(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1SaveRequest customerGroupRepositoryV1SaveRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveRequest1();
            inValue.customerGroupRepositoryV1SaveRequest = customerGroupRepositoryV1SaveRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1Save(inValue);
            return retVal.customerGroupRepositoryV1SaveResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType.customerGroupRepositoryV1SaveAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveRequest1 request) {
            return base.Channel.customerGroupRepositoryV1SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveResponse1> customerGroupRepositoryV1SaveAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1SaveRequest customerGroupRepositoryV1SaveRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1SaveRequest1();
            inValue.customerGroupRepositoryV1SaveRequest = customerGroupRepositoryV1SaveRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType.customerGroupRepositoryV1DeleteById(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdRequest1 request) {
            return base.Channel.customerGroupRepositoryV1DeleteById(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1DeleteByIdResponse customerGroupRepositoryV1DeleteById(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1DeleteByIdRequest customerGroupRepositoryV1DeleteByIdRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdRequest1();
            inValue.customerGroupRepositoryV1DeleteByIdRequest = customerGroupRepositoryV1DeleteByIdRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1DeleteById(inValue);
            return retVal.customerGroupRepositoryV1DeleteByIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType.customerGroupRepositoryV1DeleteByIdAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdRequest1 request) {
            return base.Channel.customerGroupRepositoryV1DeleteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdResponse1> customerGroupRepositoryV1DeleteByIdAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.CustomerGroupRepositoryV1DeleteByIdRequest customerGroupRepositoryV1DeleteByIdRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1DeleteByIdRequest1();
            inValue.customerGroupRepositoryV1DeleteByIdRequest = customerGroupRepositoryV1DeleteByIdRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustGroupRespository.customerGroupRepositoryV1PortType)(this)).customerGroupRepositoryV1DeleteByIdAsync(inValue);
        }
    }
}
