//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class GenericFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors {
            get {
                return this.wrappedErrorsField;
            }
            set {
                this.wrappedErrorsField = value;
                this.RaisePropertyChanged("WrappedErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class GenericFaultParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class WrappedError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cartIdField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cartId {
            get {
                return this.cartIdField;
            }
            set {
                this.cartIdField = value;
                this.RaisePropertyChanged("cartId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1", ConfigurationName="MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType")]
    public interface sizzixB2bPreOrdersPreOrdersServiceV1PortType {
        
        // CODEGEN: Generating message contract since the operation sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.GenericFault), Action="sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1 sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1> sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sizzixB2bPreOrdersPreOrdersServiceV1GetList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bPreOrdersPreOrdersServiceV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.GenericFault), Action="sizzixB2bPreOrdersPreOrdersServiceV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1 sizzixB2bPreOrdersPreOrdersServiceV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bPreOrdersPreOrdersServiceV1GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1> sizzixB2bPreOrdersPreOrdersServiceV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
            "erviceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest;
        
        public sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1() {
        }
        
        public sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest) {
            this.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest = sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
            "erviceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse;
        
        public sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1() {
        }
        
        public sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse) {
            this.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse = sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class SizzixB2bPreOrdersPreOrdersServiceV1GetListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cartIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cartId {
            get {
                return this.cartIdField;
            }
            set {
                this.cartIdField = value;
                this.RaisePropertyChanged("cartId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class SizzixB2bPreOrdersPreOrdersServiceV1GetListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private QuoteDataCartItemInterface[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public QuoteDataCartItemInterface[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class QuoteDataCartItemInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int itemIdField;
        
        private bool itemIdFieldSpecified;
        
        private string skuField;
        
        private float qtyField;
        
        private string nameField;
        
        private float priceField;
        
        private bool priceFieldSpecified;
        
        private string productTypeField;
        
        private string quoteIdField;
        
        private QuoteDataProductOptionInterface productOptionField;
        
        private QuoteDataCartItemExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int itemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("itemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemIdSpecified {
            get {
                return this.itemIdFieldSpecified;
            }
            set {
                this.itemIdFieldSpecified = value;
                this.RaisePropertyChanged("itemIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public float price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string productType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
                this.RaisePropertyChanged("productType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string quoteId {
            get {
                return this.quoteIdField;
            }
            set {
                this.quoteIdField = value;
                this.RaisePropertyChanged("quoteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public QuoteDataProductOptionInterface productOption {
            get {
                return this.productOptionField;
            }
            set {
                this.productOptionField = value;
                this.RaisePropertyChanged("productOption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public QuoteDataCartItemExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class QuoteDataProductOptionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private QuoteDataProductOptionExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public QuoteDataProductOptionExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class QuoteDataProductOptionExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CatalogDataCustomOptionInterface[] customOptionsField;
        
        private BundleDataBundleOptionInterface[] bundleOptionsField;
        
        private ConfigurableProductDataConfigurableItemOptionValueInterface[] configurableItemOptionsField;
        
        private DownloadableDataDownloadableOptionInterface downloadableOptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CatalogDataCustomOptionInterface[] customOptions {
            get {
                return this.customOptionsField;
            }
            set {
                this.customOptionsField = value;
                this.RaisePropertyChanged("customOptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BundleDataBundleOptionInterface[] bundleOptions {
            get {
                return this.bundleOptionsField;
            }
            set {
                this.bundleOptionsField = value;
                this.RaisePropertyChanged("bundleOptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ConfigurableProductDataConfigurableItemOptionValueInterface[] configurableItemOptions {
            get {
                return this.configurableItemOptionsField;
            }
            set {
                this.configurableItemOptionsField = value;
                this.RaisePropertyChanged("configurableItemOptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DownloadableDataDownloadableOptionInterface downloadableOption {
            get {
                return this.downloadableOptionField;
            }
            set {
                this.downloadableOptionField = value;
                this.RaisePropertyChanged("downloadableOption");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class CatalogDataCustomOptionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string optionIdField;
        
        private string optionValueField;
        
        private CatalogDataCustomOptionExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string optionId {
            get {
                return this.optionIdField;
            }
            set {
                this.optionIdField = value;
                this.RaisePropertyChanged("optionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string optionValue {
            get {
                return this.optionValueField;
            }
            set {
                this.optionValueField = value;
                this.RaisePropertyChanged("optionValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CatalogDataCustomOptionExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class CatalogDataCustomOptionExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkDataImageContentInterface fileInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkDataImageContentInterface fileInfo {
            get {
                return this.fileInfoField;
            }
            set {
                this.fileInfoField = value;
                this.RaisePropertyChanged("fileInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class FrameworkDataImageContentInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string base64EncodedDataField;
        
        private string typeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string base64EncodedData {
            get {
                return this.base64EncodedDataField;
            }
            set {
                this.base64EncodedDataField = value;
                this.RaisePropertyChanged("base64EncodedData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class BundleDataBundleOptionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int optionIdField;
        
        private int optionQtyField;
        
        private int[] optionSelectionsField;
        
        private BundleDataBundleOptionExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int optionId {
            get {
                return this.optionIdField;
            }
            set {
                this.optionIdField = value;
                this.RaisePropertyChanged("optionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int optionQty {
            get {
                return this.optionQtyField;
            }
            set {
                this.optionQtyField = value;
                this.RaisePropertyChanged("optionQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public int[] optionSelections {
            get {
                return this.optionSelectionsField;
            }
            set {
                this.optionSelectionsField = value;
                this.RaisePropertyChanged("optionSelections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public BundleDataBundleOptionExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class BundleDataBundleOptionExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class ConfigurableProductDataConfigurableItemOptionValueInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string optionIdField;
        
        private int optionValueField;
        
        private bool optionValueFieldSpecified;
        
        private ConfigurableProductDataConfigurableItemOptionValueExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string optionId {
            get {
                return this.optionIdField;
            }
            set {
                this.optionIdField = value;
                this.RaisePropertyChanged("optionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int optionValue {
            get {
                return this.optionValueField;
            }
            set {
                this.optionValueField = value;
                this.RaisePropertyChanged("optionValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optionValueSpecified {
            get {
                return this.optionValueFieldSpecified;
            }
            set {
                this.optionValueFieldSpecified = value;
                this.RaisePropertyChanged("optionValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ConfigurableProductDataConfigurableItemOptionValueExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class ConfigurableProductDataConfigurableItemOptionValueExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class DownloadableDataDownloadableOptionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int[] downloadableLinksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public int[] downloadableLinks {
            get {
                return this.downloadableLinksField;
            }
            set {
                this.downloadableLinksField = value;
                this.RaisePropertyChanged("downloadableLinks");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
        "erviceV1")]
    public partial class QuoteDataCartItemExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
            "erviceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1GetListRequest sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest;
        
        public sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1() {
        }
        
        public sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1GetListRequest sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest) {
            this.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest = sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bPreOrdersPreOrdersS" +
            "erviceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1GetListResponse sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse;
        
        public sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1() {
        }
        
        public sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1GetListResponse sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse) {
            this.sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse = sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sizzixB2bPreOrdersPreOrdersServiceV1PortTypeChannel : Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sizzixB2bPreOrdersPreOrdersServiceV1PortTypeClient : System.ServiceModel.ClientBase<Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType>, Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType {
        
        public sizzixB2bPreOrdersPreOrdersServiceV1PortTypeClient() {
        }
        
        public sizzixB2bPreOrdersPreOrdersServiceV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sizzixB2bPreOrdersPreOrdersServiceV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bPreOrdersPreOrdersServiceV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bPreOrdersPreOrdersServiceV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1 request) {
            return base.Channel.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1();
            inValue.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest = sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType)(this)).sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatus(inValue);
            return retVal.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1 request) {
            return base.Channel.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusResponse1> sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest1();
            inValue.sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest = sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType)(this)).sizzixB2bPreOrdersPreOrdersServiceV1SetPreOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType.sizzixB2bPreOrdersPreOrdersServiceV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1 request) {
            return base.Channel.sizzixB2bPreOrdersPreOrdersServiceV1GetList(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1GetListResponse sizzixB2bPreOrdersPreOrdersServiceV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1GetListRequest sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1();
            inValue.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest = sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType)(this)).sizzixB2bPreOrdersPreOrdersServiceV1GetList(inValue);
            return retVal.sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType.sizzixB2bPreOrdersPreOrdersServiceV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1 request) {
            return base.Channel.sizzixB2bPreOrdersPreOrdersServiceV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListResponse1> sizzixB2bPreOrdersPreOrdersServiceV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.SizzixB2bPreOrdersPreOrdersServiceV1GetListRequest sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest1();
            inValue.sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest = sizzixB2bPreOrdersPreOrdersServiceV1GetListRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoPreOrderItems.sizzixB2bPreOrdersPreOrdersServiceV1PortType)(this)).sizzixB2bPreOrdersPreOrdersServiceV1GetListAsync(inValue);
        }
    }
}
