//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class GenericFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors {
            get {
                return this.wrappedErrorsField;
            }
            set {
                this.wrappedErrorsField = value;
                this.RaisePropertyChanged("WrappedErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class GenericFaultParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class WrappedError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class SizzixB2bAccountMessagesMessageServiceV1CreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class SizzixB2bAccountMessagesDataAttachmentDataInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private string base64ImageStringField;
        
        private string fileExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string base64ImageString {
            get {
                return this.base64ImageStringField;
            }
            set {
                this.base64ImageStringField = value;
                this.RaisePropertyChanged("base64ImageString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
                this.RaisePropertyChanged("fileExtension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class SizzixB2bAccountMessagesDataMessageInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int threadIdField;
        
        private string recipientField;
        
        private string senderField;
        
        private string subjectField;
        
        private string bodyField;
        
        private string createdAtField;
        
        private SizzixB2bAccountMessagesDataAttachmentDataInterface[] base64AttachmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int threadId {
            get {
                return this.threadIdField;
            }
            set {
                this.threadIdField = value;
                this.RaisePropertyChanged("threadId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string createdAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("createdAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SizzixB2bAccountMessagesDataAttachmentDataInterface[] base64Attachments {
            get {
                return this.base64AttachmentsField;
            }
            set {
                this.base64AttachmentsField = value;
                this.RaisePropertyChanged("base64Attachments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class SizzixB2bAccountMessagesMessageServiceV1CreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SizzixB2bAccountMessagesDataMessageInterface[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SizzixB2bAccountMessagesDataMessageInterface[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1", ConfigurationName="MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType")]
    public interface sizzixB2bAccountMessagesMessageServiceV1PortType {
        
        // CODEGEN: Generating message contract since the operation sizzixB2bAccountMessagesMessageServiceV1Create is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesMessageServiceV1Create", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.GenericFault), Action="sizzixB2bAccountMessagesMessageServiceV1Create", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateResponse1 sizzixB2bAccountMessagesMessageServiceV1Create(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesMessageServiceV1Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateResponse1> sizzixB2bAccountMessagesMessageServiceV1CreateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sizzixB2bAccountMessagesMessageServiceV1Update is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesMessageServiceV1Update", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.GenericFault), Action="sizzixB2bAccountMessagesMessageServiceV1Update", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1 sizzixB2bAccountMessagesMessageServiceV1Update(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesMessageServiceV1Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1> sizzixB2bAccountMessagesMessageServiceV1UpdateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sizzixB2bAccountMessagesMessageServiceV1Delete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesMessageServiceV1Delete", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.GenericFault), Action="sizzixB2bAccountMessagesMessageServiceV1Delete", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1 sizzixB2bAccountMessagesMessageServiceV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesMessageServiceV1Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1> sizzixB2bAccountMessagesMessageServiceV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesMessageServiceV1CreateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
            "ageServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1CreateRequest sizzixB2bAccountMessagesMessageServiceV1CreateRequest;
        
        public sizzixB2bAccountMessagesMessageServiceV1CreateRequest1() {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1CreateRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1CreateRequest sizzixB2bAccountMessagesMessageServiceV1CreateRequest) {
            this.sizzixB2bAccountMessagesMessageServiceV1CreateRequest = sizzixB2bAccountMessagesMessageServiceV1CreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesMessageServiceV1CreateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
            "ageServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1CreateResponse sizzixB2bAccountMessagesMessageServiceV1CreateResponse;
        
        public sizzixB2bAccountMessagesMessageServiceV1CreateResponse1() {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1CreateResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1CreateResponse sizzixB2bAccountMessagesMessageServiceV1CreateResponse) {
            this.sizzixB2bAccountMessagesMessageServiceV1CreateResponse = sizzixB2bAccountMessagesMessageServiceV1CreateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class SizzixB2bAccountMessagesMessageServiceV1UpdateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchCriteria searchCriteriaField;
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteria searchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("searchCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class FrameworkSearchCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups {
            get {
                return this.filterGroupsField;
            }
            set {
                this.filterGroupsField = value;
                this.RaisePropertyChanged("filterGroups");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders {
            get {
                return this.sortOrdersField;
            }
            set {
                this.sortOrdersField = value;
                this.RaisePropertyChanged("sortOrders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
                this.RaisePropertyChanged("pageSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified {
            get {
                return this.currentPageFieldSpecified;
            }
            set {
                this.currentPageFieldSpecified = value;
                this.RaisePropertyChanged("currentPageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class FrameworkSearchFilterGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
                this.RaisePropertyChanged("filters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class FrameworkFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType {
            get {
                return this.conditionTypeField;
            }
            set {
                this.conditionTypeField = value;
                this.RaisePropertyChanged("conditionType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class FrameworkSortOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("direction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class SizzixB2bAccountMessagesMessageServiceV1UpdateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
            "ageServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1UpdateRequest sizzixB2bAccountMessagesMessageServiceV1UpdateRequest;
        
        public sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1() {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1UpdateRequest sizzixB2bAccountMessagesMessageServiceV1UpdateRequest) {
            this.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest = sizzixB2bAccountMessagesMessageServiceV1UpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
            "ageServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1UpdateResponse sizzixB2bAccountMessagesMessageServiceV1UpdateResponse;
        
        public sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1() {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1UpdateResponse sizzixB2bAccountMessagesMessageServiceV1UpdateResponse) {
            this.sizzixB2bAccountMessagesMessageServiceV1UpdateResponse = sizzixB2bAccountMessagesMessageServiceV1UpdateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class SizzixB2bAccountMessagesMessageServiceV1DeleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchCriteria searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteria searchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("searchCriteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
        "ageServiceV1")]
    public partial class SizzixB2bAccountMessagesMessageServiceV1DeleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
            "ageServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1DeleteRequest sizzixB2bAccountMessagesMessageServiceV1DeleteRequest;
        
        public sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1() {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1DeleteRequest sizzixB2bAccountMessagesMessageServiceV1DeleteRequest) {
            this.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest = sizzixB2bAccountMessagesMessageServiceV1DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesMess" +
            "ageServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1DeleteResponse sizzixB2bAccountMessagesMessageServiceV1DeleteResponse;
        
        public sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1() {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1DeleteResponse sizzixB2bAccountMessagesMessageServiceV1DeleteResponse) {
            this.sizzixB2bAccountMessagesMessageServiceV1DeleteResponse = sizzixB2bAccountMessagesMessageServiceV1DeleteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sizzixB2bAccountMessagesMessageServiceV1PortTypeChannel : Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sizzixB2bAccountMessagesMessageServiceV1PortTypeClient : System.ServiceModel.ClientBase<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType>, Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType {
        
        public sizzixB2bAccountMessagesMessageServiceV1PortTypeClient() {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bAccountMessagesMessageServiceV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType.sizzixB2bAccountMessagesMessageServiceV1Create(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesMessageServiceV1Create(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1CreateResponse sizzixB2bAccountMessagesMessageServiceV1Create(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1CreateRequest sizzixB2bAccountMessagesMessageServiceV1CreateRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateRequest1();
            inValue.sizzixB2bAccountMessagesMessageServiceV1CreateRequest = sizzixB2bAccountMessagesMessageServiceV1CreateRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType)(this)).sizzixB2bAccountMessagesMessageServiceV1Create(inValue);
            return retVal.sizzixB2bAccountMessagesMessageServiceV1CreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType.sizzixB2bAccountMessagesMessageServiceV1CreateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesMessageServiceV1CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateResponse1> sizzixB2bAccountMessagesMessageServiceV1CreateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1CreateRequest sizzixB2bAccountMessagesMessageServiceV1CreateRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1CreateRequest1();
            inValue.sizzixB2bAccountMessagesMessageServiceV1CreateRequest = sizzixB2bAccountMessagesMessageServiceV1CreateRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType)(this)).sizzixB2bAccountMessagesMessageServiceV1CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType.sizzixB2bAccountMessagesMessageServiceV1Update(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesMessageServiceV1Update(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1UpdateResponse sizzixB2bAccountMessagesMessageServiceV1Update(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1UpdateRequest sizzixB2bAccountMessagesMessageServiceV1UpdateRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1();
            inValue.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest = sizzixB2bAccountMessagesMessageServiceV1UpdateRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType)(this)).sizzixB2bAccountMessagesMessageServiceV1Update(inValue);
            return retVal.sizzixB2bAccountMessagesMessageServiceV1UpdateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType.sizzixB2bAccountMessagesMessageServiceV1UpdateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesMessageServiceV1UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateResponse1> sizzixB2bAccountMessagesMessageServiceV1UpdateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1UpdateRequest sizzixB2bAccountMessagesMessageServiceV1UpdateRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest1();
            inValue.sizzixB2bAccountMessagesMessageServiceV1UpdateRequest = sizzixB2bAccountMessagesMessageServiceV1UpdateRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType)(this)).sizzixB2bAccountMessagesMessageServiceV1UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType.sizzixB2bAccountMessagesMessageServiceV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesMessageServiceV1Delete(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1DeleteResponse sizzixB2bAccountMessagesMessageServiceV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1DeleteRequest sizzixB2bAccountMessagesMessageServiceV1DeleteRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1();
            inValue.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest = sizzixB2bAccountMessagesMessageServiceV1DeleteRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType)(this)).sizzixB2bAccountMessagesMessageServiceV1Delete(inValue);
            return retVal.sizzixB2bAccountMessagesMessageServiceV1DeleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType.sizzixB2bAccountMessagesMessageServiceV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesMessageServiceV1DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteResponse1> sizzixB2bAccountMessagesMessageServiceV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.SizzixB2bAccountMessagesMessageServiceV1DeleteRequest sizzixB2bAccountMessagesMessageServiceV1DeleteRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest1();
            inValue.sizzixB2bAccountMessagesMessageServiceV1DeleteRequest = sizzixB2bAccountMessagesMessageServiceV1DeleteRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountMessages.sizzixB2bAccountMessagesMessageServiceV1PortType)(this)).sizzixB2bAccountMessagesMessageServiceV1DeleteAsync(inValue);
        }
    }
}
