//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magento_Version2_NAV_Integration_Sizzix.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9147/EllisonDev/WS/Ellison%20Europe%20Ltd./Page/Customer")]
        public string Magento_Version2_NAV_Integration_Customer_service_Customer_Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_Customer_service_Customer_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9047/EllisonDev/WS/Ellison%20Europe%20Ltd./Page/Item")]
        public string Magento_Version2_NAV_Integration_Item_Service_Item_Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_Item_Service_Item_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9047/EllisonDev/WS/Ellison%20Europe%20Ltd./Page/ItemVariants")]
        public string Magento_Version2_NAV_Integration_ItemVariant_ItemVariants_Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_ItemVariant_ItemVariants_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9147/EllisonDev/WS/Ellison%20Europe%20Ltd./Codeunit/MagentoFunct" +
            "ions")]
        public string Magento_Version2_NAV_Integration_NavMagFunctions_MagentoFunctions {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_NavMagFunctions_MagentoFunctions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9147/EllisonDev/WS/Ellison%20Europe%20Ltd./Page/SalesOrder")]
        public string Magento_Version2_NAV_Integration_SalesOrder_service_SalesOrder_Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_SalesOrder_service_SalesOrder_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sizzix-b2b.c3preview.co.uk/soap/b2b_gbp?services=quoteCartRepositoryV1")]
        public string Magento_Version2_NAV_Integration_WIP_MagentoQuoteB2BWeb_quoteCartRepositoryV1Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_WIP_MagentoQuoteB2BWeb_quoteCartRepositoryV1Serv" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9047/EllisonDev/WS/Ellison%20Europe%20Ltd./Page/MagInteraction")]
        public string Magento_Version2_NAV_Integration_Sizzix_Interactions_MagInteraction_Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_Sizzix_Interactions_MagInteraction_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9147/EllisonDev/WS/Ellison%20Europe%20Ltd./Page/Salespersons")]
        public string Magento_Version2_NAV_Integration_Sizzix_Salespersons_Salespersons_Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_Sizzix_Salespersons_Salespersons_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9147/EllisonDev/WS/Ellison%20Europe%20Ltd./Page/SalesLineDiscoun" +
            "ts")]
        public string Magento_Version2_NAV_Integration_Sizzix_SalesPrices_SalesLineDiscounts_Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_Sizzix_SalesPrices_SalesLineDiscounts_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:9147/EllisonDev/WS/Ellison%20Europe%20Ltd./Page/MagentoInteracti" +
            "onAttachments")]
        public string Magento_Version2_NAV_Integration_Sizzix_Interaction_Attachment_Service_MagentoInteractionAttachments_Service {
            get {
                return ((string)(this["Magento_Version2_NAV_Integration_Sizzix_Interaction_Attachment_Service_MagentoInt" +
                    "eractionAttachments_Service"]));
            }
        }
    }
}
