//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class GenericFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors {
            get {
                return this.wrappedErrorsField;
            }
            set {
                this.wrappedErrorsField = value;
                this.RaisePropertyChanged("WrappedErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class GenericFaultParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class WrappedError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class SizzixB2bAccountMessagesDataAccountCoordinatorInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string base64ImageStringField;
        
        private string navIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string base64ImageString {
            get {
                return this.base64ImageStringField;
            }
            set {
                this.base64ImageStringField = value;
                this.RaisePropertyChanged("base64ImageString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string navId {
            get {
                return this.navIdField;
            }
            set {
                this.navIdField = value;
                this.RaisePropertyChanged("navId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SizzixB2bAccountMessagesDataAccountCoordinatorInterface accountCoordinatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SizzixB2bAccountMessagesDataAccountCoordinatorInterface accountCoordinator {
            get {
                return this.accountCoordinatorField;
            }
            set {
                this.accountCoordinatorField = value;
                this.RaisePropertyChanged("accountCoordinator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1", ConfigurationName="MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1P" +
        "ortType")]
    public interface sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType {
        
        // CODEGEN: Generating message contract since the operation sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.GenericFault), Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1 sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1> sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.GenericFault), Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1 sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1> sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.GenericFault), Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1 sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1> sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
            "untCoordinatorServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest;
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1() {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest) {
            this.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
            "untCoordinatorServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse;
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1() {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse) {
            this.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse = sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchCriteria searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteria searchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("searchCriteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class FrameworkSearchCriteria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups {
            get {
                return this.filterGroupsField;
            }
            set {
                this.filterGroupsField = value;
                this.RaisePropertyChanged("filterGroups");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders {
            get {
                return this.sortOrdersField;
            }
            set {
                this.sortOrdersField = value;
                this.RaisePropertyChanged("sortOrders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
                this.RaisePropertyChanged("pageSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified {
            get {
                return this.currentPageFieldSpecified;
            }
            set {
                this.currentPageFieldSpecified = value;
                this.RaisePropertyChanged("currentPageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class FrameworkSearchFilterGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
                this.RaisePropertyChanged("filters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class FrameworkFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType {
            get {
                return this.conditionTypeField;
            }
            set {
                this.conditionTypeField = value;
                this.RaisePropertyChanged("conditionType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class FrameworkSortOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("direction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SizzixB2bAccountMessagesDataAccountCoordinatorSearchResultsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SizzixB2bAccountMessagesDataAccountCoordinatorSearchResultsInterface result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class SizzixB2bAccountMessagesDataAccountCoordinatorSearchResultsInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SizzixB2bAccountMessagesDataAccountCoordinatorInterface[] itemsField;
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SizzixB2bAccountMessagesDataAccountCoordinatorInterface[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FrameworkSearchCriteriaInterface searchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("searchCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class FrameworkSearchCriteriaInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups {
            get {
                return this.filterGroupsField;
            }
            set {
                this.filterGroupsField = value;
                this.RaisePropertyChanged("filterGroups");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders {
            get {
                return this.sortOrdersField;
            }
            set {
                this.sortOrdersField = value;
                this.RaisePropertyChanged("sortOrders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
                this.RaisePropertyChanged("pageSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified {
            get {
                return this.currentPageFieldSpecified;
            }
            set {
                this.currentPageFieldSpecified = value;
                this.RaisePropertyChanged("currentPageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
            "untCoordinatorServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest;
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1() {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest) {
            this.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
            "untCoordinatorServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse;
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1() {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse) {
            this.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse = sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkSearchCriteria searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteria searchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("searchCriteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
        "untCoordinatorServiceV1")]
    public partial class SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
            "untCoordinatorServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest;
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1() {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest) {
            this.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bAccountMessagesAcco" +
            "untCoordinatorServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse;
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1() {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse) {
            this.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse = sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortTypeChannel : Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortTypeClient : System.ServiceModel.ClientBase<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType>, Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType {
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortTypeClient() {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType.sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1();
            inValue.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType)(this)).sizzixB2bAccountMessagesAccountCoordinatorServiceV1Save(inValue);
            return retVal.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveResponse1> sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest1();
            inValue.sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType)(this)).sizzixB2bAccountMessagesAccountCoordinatorServiceV1SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1();
            inValue.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType)(this)).sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetList(inValue);
            return retVal.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListResponse1> sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest1();
            inValue.sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType)(this)).sizzixB2bAccountMessagesAccountCoordinatorServiceV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType.sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1();
            inValue.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType)(this)).sizzixB2bAccountMessagesAccountCoordinatorServiceV1Delete(inValue);
            return retVal.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1 request) {
            return base.Channel.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteResponse1> sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.SizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest1();
            inValue.sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest = sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAccountCoordinatorB2B.sizzixB2bAccountMessagesAccountCoordinatorServiceV1PortType)(this)).sizzixB2bAccountMessagesAccountCoordinatorServiceV1DeleteAsync(inValue);
        }
    }
}
