//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1")]
    public partial class GenericFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors {
            get {
                return this.wrappedErrorsField;
            }
            set {
                this.wrappedErrorsField = value;
                this.RaisePropertyChanged("WrappedErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1")]
    public partial class GenericFaultParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1")]
    public partial class WrappedError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1")]
    public partial class SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1")]
    public partial class SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1", ConfigurationName="MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType" +
        "")]
    public interface sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType {
        
        // CODEGEN: Generating message contract since the operation sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.GenericFault), Action="sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1 sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1> sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sizzixB2bCustomerPricingSaleDiscountsServiceV1Create is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bCustomerPricingSaleDiscountsServiceV1Create", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.GenericFault), Action="sizzixB2bCustomerPricingSaleDiscountsServiceV1Create", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1 sizzixB2bCustomerPricingSaleDiscountsServiceV1Create(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bCustomerPricingSaleDiscountsServiceV1Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1> sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
            "DiscountsServiceV1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest;
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1() {
        }
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest) {
            this.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest = sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
            "DiscountsServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse;
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1() {
        }
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse) {
            this.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse = sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1")]
    public partial class SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SizzixB2bCustomerPricingDataDiscountInterface[] discountsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SizzixB2bCustomerPricingDataDiscountInterface[] discounts {
            get {
                return this.discountsField;
            }
            set {
                this.discountsField = value;
                this.RaisePropertyChanged("discounts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1")]
    public partial class SizzixB2bCustomerPricingDataDiscountInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private string custGroupField;
        
        private string typeField;
        
        private string amountField;
        
        private string startDateField;
        
        private string endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string custGroup {
            get {
                return this.custGroupField;
            }
            set {
                this.custGroupField = value;
                this.RaisePropertyChanged("custGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
        "DiscountsServiceV1")]
    public partial class SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
            "DiscountsServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest;
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1() {
        }
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest) {
            this.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest = sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=sizzixB2bCustomerPricingSale" +
            "DiscountsServiceV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse;
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1() {
        }
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse) {
            this.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse = sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sizzixB2bCustomerPricingSaleDiscountsServiceV1PortTypeChannel : Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sizzixB2bCustomerPricingSaleDiscountsServiceV1PortTypeClient : System.ServiceModel.ClientBase<Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType>, Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType {
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1PortTypeClient() {
        }
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bCustomerPricingSaleDiscountsServiceV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1 request) {
            return base.Channel.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1();
            inValue.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest = sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType)(this)).sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRules(inValue);
            return retVal.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1 request) {
            return base.Channel.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesResponse1> sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest1();
            inValue.sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest = sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType)(this)).sizzixB2bCustomerPricingSaleDiscountsServiceV1ClearDownRulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType.sizzixB2bCustomerPricingSaleDiscountsServiceV1Create(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1 request) {
            return base.Channel.sizzixB2bCustomerPricingSaleDiscountsServiceV1Create(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse sizzixB2bCustomerPricingSaleDiscountsServiceV1Create(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1();
            inValue.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest = sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType)(this)).sizzixB2bCustomerPricingSaleDiscountsServiceV1Create(inValue);
            return retVal.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1 request) {
            return base.Channel.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateResponse1> sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.SizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest1();
            inValue.sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest = sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoCustomerPriceGroups.sizzixB2bCustomerPricingSaleDiscountsServiceV1PortType)(this)).sizzixB2bCustomerPricingSaleDiscountsServiceV1CreateAsync(inValue);
        }
    }
}
