//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class GenericFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors {
            get {
                return this.wrappedErrorsField;
            }
            set {
                this.wrappedErrorsField = value;
                this.RaisePropertyChanged("WrappedErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class GenericFaultParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class WrappedError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class EavDataAttributeOptionLabelInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int storeIdField;
        
        private bool storeIdFieldSpecified;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
                this.RaisePropertyChanged("storeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool storeIdSpecified {
            get {
                return this.storeIdFieldSpecified;
            }
            set {
                this.storeIdFieldSpecified = value;
                this.RaisePropertyChanged("storeIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class EavDataAttributeOptionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private string valueField;
        
        private int sortOrderField;
        
        private bool sortOrderFieldSpecified;
        
        private bool isDefaultField;
        
        private bool isDefaultFieldSpecified;
        
        private EavDataAttributeOptionLabelInterface[] storeLabelsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int sortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
                this.RaisePropertyChanged("sortOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortOrderSpecified {
            get {
                return this.sortOrderFieldSpecified;
            }
            set {
                this.sortOrderFieldSpecified = value;
                this.RaisePropertyChanged("sortOrderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
                this.RaisePropertyChanged("isDefault");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDefaultSpecified {
            get {
                return this.isDefaultFieldSpecified;
            }
            set {
                this.isDefaultFieldSpecified = value;
                this.RaisePropertyChanged("isDefaultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EavDataAttributeOptionLabelInterface[] storeLabels {
            get {
                return this.storeLabelsField;
            }
            set {
                this.storeLabelsField = value;
                this.RaisePropertyChanged("storeLabels");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class CatalogProductAttributeOptionManagementV1GetItemsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EavDataAttributeOptionInterface[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EavDataAttributeOptionInterface[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class CatalogProductAttributeOptionManagementV1GetItemsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attributeCode {
            get {
                return this.attributeCodeField;
            }
            set {
                this.attributeCodeField = value;
                this.RaisePropertyChanged("attributeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1", ConfigurationName="MagentoAttributes.catalogProductAttributeOptionManagementV1PortType")]
    public interface catalogProductAttributeOptionManagementV1PortType {
        
        // CODEGEN: Generating message contract since the operation catalogProductAttributeOptionManagementV1GetItems is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeOptionManagementV1GetItems", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.GenericFault), Action="catalogProductAttributeOptionManagementV1GetItems", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsResponse1 catalogProductAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeOptionManagementV1GetItems", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsResponse1> catalogProductAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogProductAttributeOptionManagementV1Add is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeOptionManagementV1Add", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.GenericFault), Action="catalogProductAttributeOptionManagementV1Add", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddResponse1 catalogProductAttributeOptionManagementV1Add(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeOptionManagementV1Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddResponse1> catalogProductAttributeOptionManagementV1AddAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogProductAttributeOptionManagementV1Delete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeOptionManagementV1Delete", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.GenericFault), Action="catalogProductAttributeOptionManagementV1Delete", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteResponse1 catalogProductAttributeOptionManagementV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeOptionManagementV1Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteResponse1> catalogProductAttributeOptionManagementV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeOptionManagementV1GetItemsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1GetItemsRequest catalogProductAttributeOptionManagementV1GetItemsRequest;
        
        public catalogProductAttributeOptionManagementV1GetItemsRequest1() {
        }
        
        public catalogProductAttributeOptionManagementV1GetItemsRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1GetItemsRequest catalogProductAttributeOptionManagementV1GetItemsRequest) {
            this.catalogProductAttributeOptionManagementV1GetItemsRequest = catalogProductAttributeOptionManagementV1GetItemsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeOptionManagementV1GetItemsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1GetItemsResponse catalogProductAttributeOptionManagementV1GetItemsResponse;
        
        public catalogProductAttributeOptionManagementV1GetItemsResponse1() {
        }
        
        public catalogProductAttributeOptionManagementV1GetItemsResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1GetItemsResponse catalogProductAttributeOptionManagementV1GetItemsResponse) {
            this.catalogProductAttributeOptionManagementV1GetItemsResponse = catalogProductAttributeOptionManagementV1GetItemsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class CatalogProductAttributeOptionManagementV1AddRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeCodeField;
        
        private EavDataAttributeOptionInterface optionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attributeCode {
            get {
                return this.attributeCodeField;
            }
            set {
                this.attributeCodeField = value;
                this.RaisePropertyChanged("attributeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public EavDataAttributeOptionInterface option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
                this.RaisePropertyChanged("option");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class CatalogProductAttributeOptionManagementV1AddResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeOptionManagementV1AddRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1AddRequest catalogProductAttributeOptionManagementV1AddRequest;
        
        public catalogProductAttributeOptionManagementV1AddRequest1() {
        }
        
        public catalogProductAttributeOptionManagementV1AddRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1AddRequest catalogProductAttributeOptionManagementV1AddRequest) {
            this.catalogProductAttributeOptionManagementV1AddRequest = catalogProductAttributeOptionManagementV1AddRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeOptionManagementV1AddResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1AddResponse catalogProductAttributeOptionManagementV1AddResponse;
        
        public catalogProductAttributeOptionManagementV1AddResponse1() {
        }
        
        public catalogProductAttributeOptionManagementV1AddResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1AddResponse catalogProductAttributeOptionManagementV1AddResponse) {
            this.catalogProductAttributeOptionManagementV1AddResponse = catalogProductAttributeOptionManagementV1AddResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class CatalogProductAttributeOptionManagementV1DeleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeCodeField;
        
        private string optionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attributeCode {
            get {
                return this.attributeCodeField;
            }
            set {
                this.attributeCodeField = value;
                this.RaisePropertyChanged("attributeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string optionId {
            get {
                return this.optionIdField;
            }
            set {
                this.optionIdField = value;
                this.RaisePropertyChanged("optionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class CatalogProductAttributeOptionManagementV1DeleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeOptionManagementV1DeleteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1DeleteRequest catalogProductAttributeOptionManagementV1DeleteRequest;
        
        public catalogProductAttributeOptionManagementV1DeleteRequest1() {
        }
        
        public catalogProductAttributeOptionManagementV1DeleteRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1DeleteRequest catalogProductAttributeOptionManagementV1DeleteRequest) {
            this.catalogProductAttributeOptionManagementV1DeleteRequest = catalogProductAttributeOptionManagementV1DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeOptionManagementV1DeleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1DeleteResponse catalogProductAttributeOptionManagementV1DeleteResponse;
        
        public catalogProductAttributeOptionManagementV1DeleteResponse1() {
        }
        
        public catalogProductAttributeOptionManagementV1DeleteResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1DeleteResponse catalogProductAttributeOptionManagementV1DeleteResponse) {
            this.catalogProductAttributeOptionManagementV1DeleteResponse = catalogProductAttributeOptionManagementV1DeleteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface catalogProductAttributeOptionManagementV1PortTypeChannel : Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class catalogProductAttributeOptionManagementV1PortTypeClient : System.ServiceModel.ClientBase<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType>, Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType {
        
        public catalogProductAttributeOptionManagementV1PortTypeClient() {
        }
        
        public catalogProductAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public catalogProductAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public catalogProductAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public catalogProductAttributeOptionManagementV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType.catalogProductAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsRequest1 request) {
            return base.Channel.catalogProductAttributeOptionManagementV1GetItems(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1GetItemsResponse catalogProductAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1GetItemsRequest catalogProductAttributeOptionManagementV1GetItemsRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsRequest1();
            inValue.catalogProductAttributeOptionManagementV1GetItemsRequest = catalogProductAttributeOptionManagementV1GetItemsRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType)(this)).catalogProductAttributeOptionManagementV1GetItems(inValue);
            return retVal.catalogProductAttributeOptionManagementV1GetItemsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType.catalogProductAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsRequest1 request) {
            return base.Channel.catalogProductAttributeOptionManagementV1GetItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsResponse1> catalogProductAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1GetItemsRequest catalogProductAttributeOptionManagementV1GetItemsRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1GetItemsRequest1();
            inValue.catalogProductAttributeOptionManagementV1GetItemsRequest = catalogProductAttributeOptionManagementV1GetItemsRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType)(this)).catalogProductAttributeOptionManagementV1GetItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType.catalogProductAttributeOptionManagementV1Add(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddRequest1 request) {
            return base.Channel.catalogProductAttributeOptionManagementV1Add(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1AddResponse catalogProductAttributeOptionManagementV1Add(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1AddRequest catalogProductAttributeOptionManagementV1AddRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddRequest1();
            inValue.catalogProductAttributeOptionManagementV1AddRequest = catalogProductAttributeOptionManagementV1AddRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType)(this)).catalogProductAttributeOptionManagementV1Add(inValue);
            return retVal.catalogProductAttributeOptionManagementV1AddResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType.catalogProductAttributeOptionManagementV1AddAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddRequest1 request) {
            return base.Channel.catalogProductAttributeOptionManagementV1AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddResponse1> catalogProductAttributeOptionManagementV1AddAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1AddRequest catalogProductAttributeOptionManagementV1AddRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1AddRequest1();
            inValue.catalogProductAttributeOptionManagementV1AddRequest = catalogProductAttributeOptionManagementV1AddRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType)(this)).catalogProductAttributeOptionManagementV1AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType.catalogProductAttributeOptionManagementV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteRequest1 request) {
            return base.Channel.catalogProductAttributeOptionManagementV1Delete(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1DeleteResponse catalogProductAttributeOptionManagementV1Delete(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1DeleteRequest catalogProductAttributeOptionManagementV1DeleteRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteRequest1();
            inValue.catalogProductAttributeOptionManagementV1DeleteRequest = catalogProductAttributeOptionManagementV1DeleteRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType)(this)).catalogProductAttributeOptionManagementV1Delete(inValue);
            return retVal.catalogProductAttributeOptionManagementV1DeleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType.catalogProductAttributeOptionManagementV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteRequest1 request) {
            return base.Channel.catalogProductAttributeOptionManagementV1DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteResponse1> catalogProductAttributeOptionManagementV1DeleteAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogProductAttributeOptionManagementV1DeleteRequest catalogProductAttributeOptionManagementV1DeleteRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1DeleteRequest1();
            inValue.catalogProductAttributeOptionManagementV1DeleteRequest = catalogProductAttributeOptionManagementV1DeleteRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogProductAttributeOptionManagementV1PortType)(this)).catalogProductAttributeOptionManagementV1DeleteAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1", ConfigurationName="MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionMana" +
        "gementV1PortType")]
    public interface sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortType {
        
        // CODEGEN: Generating message contract since the operation sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.GenericFault), Action="sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1 sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1> sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attributeCode {
            get {
                return this.attributeCodeField;
            }
            set {
                this.attributeCodeField = value;
                this.RaisePropertyChanged("attributeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EavDataAttributeOptionInterface[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EavDataAttributeOptionInterface[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest;
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1() {
        }
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest) {
            this.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest = sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse;
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1() {
        }
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse) {
            this.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse = sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortTypeChannel : Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortTypeClient : System.ServiceModel.ClientBase<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortType>, Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortType {
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortTypeClient() {
        }
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortType.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1 request) {
            return base.Channel.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1();
            inValue.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest = sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortType)(this)).sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItems(inValue);
            return retVal.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortType.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1 request) {
            return base.Channel.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsResponse1> sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.SizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest1();
            inValue.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest = sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1PortType)(this)).sizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManagementV1GetItemsAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1", ConfigurationName="MagentoAttributes.catalogCategoryAttributeOptionManagementV1PortType")]
    public interface catalogCategoryAttributeOptionManagementV1PortType {
        
        // CODEGEN: Generating message contract since the operation catalogCategoryAttributeOptionManagementV1GetItems is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogCategoryAttributeOptionManagementV1GetItems", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.GenericFault), Action="catalogCategoryAttributeOptionManagementV1GetItems", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsResponse1 catalogCategoryAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogCategoryAttributeOptionManagementV1GetItems", ReplyAction="*")]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsResponse1> catalogCategoryAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class CatalogCategoryAttributeOptionManagementV1GetItemsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attributeCode {
            get {
                return this.attributeCodeField;
            }
            set {
                this.attributeCodeField = value;
                this.RaisePropertyChanged("attributeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
        "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
        "ementV1%2CcatalogCategoryAttributeOptionManagementV1")]
    public partial class CatalogCategoryAttributeOptionManagementV1GetItemsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EavDataAttributeOptionInterface[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EavDataAttributeOptionInterface[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogCategoryAttributeOptionManagementV1GetItemsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogCategoryAttributeOptionManagementV1GetItemsRequest catalogCategoryAttributeOptionManagementV1GetItemsRequest;
        
        public catalogCategoryAttributeOptionManagementV1GetItemsRequest1() {
        }
        
        public catalogCategoryAttributeOptionManagementV1GetItemsRequest1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogCategoryAttributeOptionManagementV1GetItemsRequest catalogCategoryAttributeOptionManagementV1GetItemsRequest) {
            this.catalogCategoryAttributeOptionManagementV1GetItemsRequest = catalogCategoryAttributeOptionManagementV1GetItemsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogCategoryAttributeOptionManagementV1GetItemsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://sizzix-b2b.c3preview.co.uk/soap/all?services=catalogProductAttributeOptio" +
            "nManagementV1%2CsizzixB2bCustomerAttributeOptionsApiCustomerAttributeOptionManag" +
            "ementV1%2CcatalogCategoryAttributeOptionManagementV1", Order=0)]
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogCategoryAttributeOptionManagementV1GetItemsResponse catalogCategoryAttributeOptionManagementV1GetItemsResponse;
        
        public catalogCategoryAttributeOptionManagementV1GetItemsResponse1() {
        }
        
        public catalogCategoryAttributeOptionManagementV1GetItemsResponse1(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogCategoryAttributeOptionManagementV1GetItemsResponse catalogCategoryAttributeOptionManagementV1GetItemsResponse) {
            this.catalogCategoryAttributeOptionManagementV1GetItemsResponse = catalogCategoryAttributeOptionManagementV1GetItemsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface catalogCategoryAttributeOptionManagementV1PortTypeChannel : Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class catalogCategoryAttributeOptionManagementV1PortTypeClient : System.ServiceModel.ClientBase<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1PortType>, Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1PortType {
        
        public catalogCategoryAttributeOptionManagementV1PortTypeClient() {
        }
        
        public catalogCategoryAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public catalogCategoryAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public catalogCategoryAttributeOptionManagementV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public catalogCategoryAttributeOptionManagementV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsResponse1 Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1PortType.catalogCategoryAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsRequest1 request) {
            return base.Channel.catalogCategoryAttributeOptionManagementV1GetItems(request);
        }
        
        public Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogCategoryAttributeOptionManagementV1GetItemsResponse catalogCategoryAttributeOptionManagementV1GetItems(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogCategoryAttributeOptionManagementV1GetItemsRequest catalogCategoryAttributeOptionManagementV1GetItemsRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsRequest1();
            inValue.catalogCategoryAttributeOptionManagementV1GetItemsRequest = catalogCategoryAttributeOptionManagementV1GetItemsRequest;
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsResponse1 retVal = ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1PortType)(this)).catalogCategoryAttributeOptionManagementV1GetItems(inValue);
            return retVal.catalogCategoryAttributeOptionManagementV1GetItemsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsResponse1> Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1PortType.catalogCategoryAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsRequest1 request) {
            return base.Channel.catalogCategoryAttributeOptionManagementV1GetItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsResponse1> catalogCategoryAttributeOptionManagementV1GetItemsAsync(Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.CatalogCategoryAttributeOptionManagementV1GetItemsRequest catalogCategoryAttributeOptionManagementV1GetItemsRequest) {
            Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsRequest1 inValue = new Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1GetItemsRequest1();
            inValue.catalogCategoryAttributeOptionManagementV1GetItemsRequest = catalogCategoryAttributeOptionManagementV1GetItemsRequest;
            return ((Magento_Version2_NAV_Integration_Sizzix.MagentoAttributes.catalogCategoryAttributeOptionManagementV1PortType)(this)).catalogCategoryAttributeOptionManagementV1GetItemsAsync(inValue);
        }
    }
}
